<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>g4at-ac-scanner</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <!-- un solo .exe autocontenido (se publica con el script de abajo) -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2592.51" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- la interfaz HTML va embebida dentro del .exe -->
    <EmbeddedResource Include="wwwroot\**\*" />
    <EmbeddedResource Include="config.json" Condition="Exists('config.json')" />
  </ItemGroup>

</Project>
